namespace RunCoach.Api.Modules.Coaching.Models.Structured;

/// <summary>
/// Post-deserialization validator for a <see cref="MesoWeekOutput"/> generated by the
/// rolling-horizon extension seam (DEC-090 D8). Enforces what Anthropic constrained decoding
/// cannot express:
/// <list type="number">
/// <item>week identity — <see cref="MesoWeekOutput.WeekNumber"/> must equal the expected
/// 1-based target week index;</item>
/// <item>day-slot completeness — at least one of the seven day slots must be a
/// <see cref="DaySlotType.Run"/> slot, so the week has something for the micro tier to expand.</item>
/// </list>
/// Pure: it does not retry, log, or throw (beyond the null guard) — callers decide policy.
/// Mirrors <see cref="MacroPlanOutputValidator"/>.
/// </summary>
/// <remarks>
/// Required on the extension path (D8) because the projection guard it protects
/// (<c>PlanProjection.Apply(MesoCycleCreated, …)</c>'s <see cref="InvalidOperationException"/> on a
/// week-number mismatch) is a hard abort. The bootstrap meso loop in
/// <c>PlanGenerationService.GeneratePlanAsync</c> has never had this validator; this closes that gap
/// only for the new rolling-horizon path — backporting it to the bootstrap loop is explicitly out
/// of scope for this PR.
/// </remarks>
public static class MesoWeekOutputValidator
{
    /// <summary>Validates a generated meso week against the expected target week index.</summary>
    /// <param name="output">The deserialized meso week output.</param>
    /// <param name="expectedWeekIndex">The 1-based week index this call was generating for.</param>
    public static MesoWeekOutputValidationResult Validate(MesoWeekOutput output, int expectedWeekIndex)
    {
        ArgumentNullException.ThrowIfNull(output);

        if (output.WeekNumber != expectedWeekIndex)
        {
            return MesoWeekOutputValidationResult.Invalid(
                MesoWeekOutputValidationViolation.WeekNumberMismatch);
        }

        var hasRunDay = output.EnumerateDays().Any(d => d.Slot.SlotType == DaySlotType.Run);
        if (!hasRunDay)
        {
            return MesoWeekOutputValidationResult.Invalid(
                MesoWeekOutputValidationViolation.NoRunDay);
        }

        return MesoWeekOutputValidationResult.Valid();
    }
}
