namespace RunCoach.Api.Modules.Coaching.Models.Structured;

/// <summary>
/// Post-deserialization cross-layer validator (F-LIVE-2). Reconciles the week-1
/// <see cref="MicroWorkoutListOutput"/> against the <see cref="MesoWeekOutput"/> it expands: the meso
/// week is the source of truth, so the micro layer must schedule exactly one workout per meso
/// <see cref="DaySlotType.Run"/> slot, on the same calendar day, of the same <see cref="WorkoutType"/>.
/// This is what Anthropic constrained decoding cannot express — the two layers are generated by
/// independent structured-output calls and can silently disagree (differing run-day count or a
/// swapped workout type), which the home page renders side by side (meso week narrative beside
/// micro workout cards). Cross-train and rest days are compared by run-day scope only: a meso
/// cross-train/rest slot is not a run day, and a micro <see cref="WorkoutType.CrossTrain"/> entry is
/// excluded from the run-workout set (mirroring the cross-train exclusion in
/// <c>RestructureConsistencyCheck</c>).
/// <para>
/// Pure: it does not retry, log, or throw (beyond the null guard) — callers decide policy. Mirrors
/// <see cref="MacroPlanOutputValidator"/>.
/// </para>
/// </summary>
public static class MesoMicroConsistencyValidator
{
    /// <summary>Validates the week-1 micro workouts against the meso week-1 template.</summary>
    /// <param name="weekOneMeso">The week-1 meso template (source of truth for the run schedule).</param>
    /// <param name="micro">The week-1 micro workout list to reconcile against it.</param>
    public static MesoMicroConsistencyResult Validate(MesoWeekOutput weekOneMeso, MicroWorkoutListOutput micro)
    {
        ArgumentNullException.ThrowIfNull(weekOneMeso);
        ArgumentNullException.ThrowIfNull(micro);

        // Expected run days from the meso template: one entry per Run slot, keyed by calendar day
        // (System.DayOfWeek: Sunday=0..Saturday=6, matching WorkoutOutput.DayOfWeek), carrying the
        // meso-assigned workout type (nullable — a Run slot may leave the type unspecified).
        var expected = new Dictionary<int, WorkoutType?>();
        foreach (var (day, slot) in weekOneMeso.EnumerateDays().Where(d => d.Slot.SlotType == DaySlotType.Run))
        {
            expected[(int)day] = slot.WorkoutType;
        }

        // Actual run workouts from the micro layer, keyed by day. Cross-train entries are not run
        // days and are excluded. A second workout on a day already seen is a duplicate: runWorkoutCount
        // counts every run workout while the dictionary dedups by day, so a duplicate inflates the
        // count above the distinct-day set and is reported rather than silently absorbed.
        var actual = new Dictionary<int, WorkoutType>();
        var runWorkoutCount = 0;
        foreach (var workout in micro.Workouts.Where(w => w.WorkoutType != WorkoutType.CrossTrain))
        {
            runWorkoutCount++;
            actual[workout.DayOfWeek] = workout.WorkoutType;
        }

        // (1) Run-day count — meso run-day count vs. micro run-workout count (a duplicate day makes
        // runWorkoutCount exceed the distinct-day dictionary size and is caught here too).
        if (runWorkoutCount != expected.Count)
        {
            return MesoMicroConsistencyResult.Invalid(MesoMicroConsistencyViolation.RunDayCountMismatch);
        }

        // (2) Run-day set membership — same day keys on both sides. Equal counts with a missing key
        // implies an extra key elsewhere, so a single containment sweep suffices.
        if (!expected.Keys.All(actual.ContainsKey))
        {
            return MesoMicroConsistencyResult.Invalid(MesoMicroConsistencyViolation.RunDaySetMismatch);
        }

        // (3) Per-day workout type — each meso run day that declares a type must match the micro
        // workout's type on that day. A null meso type constrains presence only (handled above).
        // Every expected key is present in actual by the containment check above.
        var typeMismatch = expected.Any(kvp => kvp.Value is not null && actual[kvp.Key] != kvp.Value.Value);
        if (typeMismatch)
        {
            return MesoMicroConsistencyResult.Invalid(MesoMicroConsistencyViolation.WorkoutTypeMismatch);
        }

        return MesoMicroConsistencyResult.Valid();
    }
}
