using System.Text.Json;
using RunCoach.Api.Modules.Coaching.Models.Structured;
using RunCoach.Api.Modules.Coaching.Onboarding;

namespace RunCoach.Api.Modules.Coaching.Adaptation;

/// <summary>
/// Pattern-B byte-stable JSON Schema dictionary for <see cref="PlanAdaptationOutput"/>
/// per DEC-058. Built once at type-load and exposed via <see cref="Frozen"/> so every
/// adaptation call ships byte-identical <c>output_config.format.schema</c> bytes — keeping
/// Anthropic's grammar cache and prompt-prefix cache hot.
/// </summary>
/// <remarks>
/// Generated by <see cref="JsonSchemaHelper.GenerateSchema{T}"/> then post-processed by
/// <see cref="AnthropicSchemaSanitizer"/> as defense-in-depth, so any forbidden keyword
/// (<c>oneOf</c>, <c>minimum</c>, <c>pattern</c>, …) a future System.Text.Json upgrade
/// might emit is stripped before the schema ships. Mirrors <c>OnboardingSchema</c>.
/// </remarks>
public static class AdaptationSchema
{
    /// <summary>
    /// The byte-stable Pattern-B schema dictionary for <see cref="PlanAdaptationOutput"/>.
    /// Built exactly once at type-load via <see cref="BuildAdaptationSchema"/>.
    /// </summary>
    public static readonly IReadOnlyDictionary<string, JsonElement> Frozen = BuildAdaptationSchema();

    /// <summary>
    /// Generates a fresh Pattern-B schema dictionary for <see cref="PlanAdaptationOutput"/>.
    /// Two consecutive calls return byte-equal payloads, so this is safe to call from tests
    /// for invariant assertions without affecting the cached <see cref="Frozen"/> instance.
    /// </summary>
    /// <returns>A sanitized, dictionary-shaped JSON schema for <see cref="PlanAdaptationOutput"/>.</returns>
    public static IReadOnlyDictionary<string, JsonElement> BuildAdaptationSchema()
    {
        var schemaNode = JsonSchemaHelper.GenerateSchema<PlanAdaptationOutput>();
        return AnthropicSchemaSanitizer.ToDictionary(schemaNode);
    }
}
