import { describe, expect, it } from 'vitest'
import { GetApiV1ConversationTurnsResponse } from '~/api/generated/zod/conversation/conversation'
import {
  buildAmberSafetyTurn,
  buildCrisisSafetyTurn,
  buildNudgeTurn,
  buildRestructureTurn,
} from '~/modules/coaching/components/conversation.fixture'
import type { ConversationTurnsResponseDto } from './conversation.model'

// Contract tripwire between the hand-written wire model (`conversation.model.ts`,
// the accurate source of truth) and the committed generated Zod schema
// (`api/generated/zod/conversation`, regenerated by the codegen drift gate from
// the backend OpenAPI document). The hand-written model exists because the
// backend schema filter cannot express C# nullability on `$ref` properties, so
// the generated schema marks `escalationLevel` / `adaptationKind` / `diff` (and
// the `before` / `after` workout cards) as always-present — which is accurate
// only for fully-populated adaptation turns.
//
// Without this spec the codegen gate is inert: a backend contract change
// (property added/removed/renamed, enum member renumbered) regenerates the Zod
// file while every other test — built from the same hand-assumed integers —
// stays green and the panel silently misroutes turns. Asserting the shared
// fixtures against the generated schema forces the paired model update the
// model's header promises.

describe('conversation wire contract vs. generated Zod schema', () => {
  // A fully-populated adaptation turn (every enum present, both diff workout
  // cards non-null) is the one shape the generated schema can validate. Parsing
  // it exercises the schema field-for-field: `strictObject` rejects an added or
  // removed property, and the literal unions reject a renumbered enum member —
  // so a backend drift that regenerated the schema would fail this assertion
  // until the hand-written model + fixtures are updated in lockstep.
  it.each([
    ['restructure', buildRestructureTurn],
    ['nudge', buildNudgeTurn],
  ])('accepts a fully-populated %s adaptation turn', (_label, build) => {
    const payload: ConversationTurnsResponseDto = { turns: [build()] }
    const result = GetApiV1ConversationTurnsResponse.safeParse(payload)
    expect(result.success, result.error?.message).toBe(true)
  })

  // Safety turns send `escalationLevel` / `adaptationKind` / `diff` as null,
  // which the generated schema's non-nullable `$ref` props cannot express — the
  // exact reason the hand-written model is the accurate contract. Locking in
  // this rejection means a future codegen/backend change that DOES emit
  // nullable variants flips this assertion and prompts a model review rather
  // than passing unnoticed.
  it.each([
    ['crisis', buildCrisisSafetyTurn],
    ['amber', buildAmberSafetyTurn],
  ])(
    'rejects a %s safety turn (null members the generated schema cannot express)',
    (_label, build) => {
      const payload = { turns: [build()] }
      const result = GetApiV1ConversationTurnsResponse.safeParse(payload)
      expect(result.success).toBe(false)
    },
  )
})
