using System.Text.Json;
using RunCoach.Api.Modules.Coaching.Models.Structured;

namespace RunCoach.Api.Modules.Coaching.Onboarding;

/// <summary>
/// Pattern-B byte-stable JSON Schema dictionary for <see cref="OnboardingTurnOutput"/>
/// per R-067 / DEC-058. The schema is built once at type-load and exposed via
/// the <see cref="Frozen"/> field so every onboarding turn ships the byte-identical
/// <c>output_config.format.schema</c> bytes — keeping Anthropic's grammar cache
/// AND prompt-prefix cache hot from turn 2 onward.
/// </summary>
/// <remarks>
/// <para>
/// Schema is generated by <see cref="JsonSchemaHelper.GenerateSchema{T}"/>
/// (which uses <c>System.Text.Json.JsonSchemaExporter</c>), then post-processed
/// by <see cref="AnthropicSchemaSanitizer"/> as defense-in-depth in case
/// any forbidden keyword (<c>pattern</c>, <c>format</c>, <c>min*</c>, <c>max*</c>,
/// <c>oneOf</c>, etc.) sneaks through a future System.Text.Json upgrade.
/// </para>
/// <para>
/// Per DEC-058: byte-stability is the load-bearing property here. The schema
/// dictionary participates in the prompt-cache prefix hash, so per-turn schema
/// mutation invalidates the cache (turning an ~70% input-token reduction into
/// 0%). The frozen instance is also the schema fed into Anthropic by
/// <see cref="ICoachingLlm.GenerateStructuredAsync{T}(string, string, IReadOnlyDictionary{string, JsonElement}?, Models.CacheControl?, CancellationToken)"/>.
/// </para>
/// </remarks>
public static class OnboardingSchema
{
    /// <summary>
    /// The byte-stable Pattern-B schema dictionary for <see cref="OnboardingTurnOutput"/>.
    /// Built exactly once at type-load via <see cref="BuildOnboardingSchema"/>.
    /// </summary>
    public static readonly IReadOnlyDictionary<string, JsonElement> Frozen = BuildOnboardingSchema();

    /// <summary>
    /// Generates a fresh Pattern-B schema dictionary for <see cref="OnboardingTurnOutput"/>.
    /// Two consecutive calls return byte-equal payloads — verified by
    /// <c>OnboardingSchemaStabilityTests</c> — so this is safe to call from
    /// tests for invariant assertions without affecting the cached
    /// <see cref="Frozen"/> instance.
    /// </summary>
    /// <returns>A sanitized, dictionary-shaped JSON schema for <see cref="OnboardingTurnOutput"/>.</returns>
    public static IReadOnlyDictionary<string, JsonElement> BuildOnboardingSchema()
    {
        var schemaNode = JsonSchemaHelper.GenerateSchema<OnboardingTurnOutput>();

        // Defense-in-depth: strip any keyword Anthropic rejects, even if the
        // current JsonSchemaExporter does not emit it — the exporter's
        // behavior is version-dependent and a System.Text.Json upgrade could
        // start emitting `format` on string properties tomorrow.
        return AnthropicSchemaSanitizer.ToDictionary(schemaNode);
    }
}
