using System.Text.Json;
using RunCoach.Api.Modules.Coaching.Models.Structured;

namespace RunCoach.Api.Modules.Coaching.Conversation;

/// <summary>
/// Pattern-B byte-stable JSON Schema dictionary for <see cref="MessageIntentOutput"/>
/// per DEC-058 (Slice 4B Unit 4). Built once at type-load and exposed via
/// <see cref="Frozen"/> so every classifier call ships byte-identical
/// <c>output_config.format.schema</c> bytes — keeping Anthropic's grammar cache and
/// prompt-prefix cache hot. Mirrors <c>AdaptationSchema</c>.
/// </summary>
/// <remarks>
/// Generated by <see cref="JsonSchemaHelper.GenerateSchema{T}"/> then post-processed by
/// <see cref="AnthropicSchemaSanitizer"/>, which strips Anthropic-forbidden keywords
/// (<c>oneOf</c>, <c>minimum</c>, <c>pattern</c>, <c>format</c>, …) and inlines any local
/// <c>$ref</c> — <see cref="MessageIntentOutput"/> reuses no record across slots so it is
/// ref-free today, but the sanitizer is defense-in-depth against a future System.Text.Json
/// change. Passing this <see cref="Frozen"/> dict to <c>GenerateStructuredAsync</c> (rather
/// than the null-schema fallback, which skips the sanitizer) is load-bearing.
/// </remarks>
public static class ClassifierSchema
{
    /// <summary>
    /// The byte-stable Pattern-B schema dictionary for <see cref="MessageIntentOutput"/>.
    /// Built exactly once at type-load via <see cref="BuildClassifierSchema"/>.
    /// </summary>
    public static readonly IReadOnlyDictionary<string, JsonElement> Frozen = BuildClassifierSchema();

    /// <summary>
    /// Generates a fresh Pattern-B schema dictionary for <see cref="MessageIntentOutput"/>.
    /// Two consecutive calls return byte-equal payloads, so this is safe to call from tests
    /// for invariant assertions without affecting the cached <see cref="Frozen"/> instance.
    /// </summary>
    /// <returns>A sanitized, dictionary-shaped JSON schema for <see cref="MessageIntentOutput"/>.</returns>
    public static IReadOnlyDictionary<string, JsonElement> BuildClassifierSchema()
    {
        var schemaNode = JsonSchemaHelper.GenerateSchema<MessageIntentOutput>();
        return AnthropicSchemaSanitizer.ToDictionary(schemaNode);
    }
}
