using System.Collections.Immutable;
using RunCoach.Api.Modules.Training.Models;

namespace RunCoach.Api.Modules.Coaching.Models;

/// <summary>
/// A high-level training plan with phased periodization,
/// generated by the coaching LLM.
/// </summary>
public sealed record MacroPlan(
    Guid PlanId,
    Guid UserId,
    GoalState GoalSnapshot,
    ImmutableArray<PlanPhase> Phases,
    DateTime CreatedOn,
    string GeneratedBy);
